/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barquero.views;

import barquero.AlgoritmoSolucion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alexs
 */
public class Enemigos extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form NewJFrame
     */
    public Enemigos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMantis = new javax.swing.JLabel();
        lblLechuga = new javax.swing.JLabel();
        lblRaton = new javax.swing.JLabel();
        lblSerpiente = new javax.swing.JLabel();
        lblHalcon = new javax.swing.JLabel();
        btnAnimar = new javax.swing.JButton();
        lblBote = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblCol = new javax.swing.JLabel();
        lblSaltamontes = new javax.swing.JLabel();
        lblPaisaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AlgoritmoBarquero");
        setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMantis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barquero/assets/planta.png"))); // NOI18N
        getContentPane().add(lblMantis, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        lblLechuga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barquero/assets/caribu.png"))); // NOI18N
        getContentPane().add(lblLechuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        lblRaton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barquero/assets/rata.png"))); // NOI18N
        getContentPane().add(lblRaton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        lblSerpiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barquero/assets/gato.png"))); // NOI18N
        getContentPane().add(lblSerpiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        lblHalcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barquero/assets/tiranosaurio.png"))); // NOI18N
        getContentPane().add(lblHalcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        btnAnimar.setText("Animar");
        btnAnimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnimar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 110, 30));

        lblBote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barquero/assets/boat (1).png"))); // NOI18N
        getContentPane().add(lblBote, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 80, 100));

        jButton1.setText("Información");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 120, 30));

        lblCol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barquero/assets/coles-de-bruselas (1).png"))); // NOI18N
        getContentPane().add(lblCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        lblSaltamontes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barquero/assets/saltamontes_1.png"))); // NOI18N
        getContentPane().add(lblSaltamontes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lblPaisaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barquero/assets/Fondo.jpg"))); // NOI18N
        getContentPane().add(lblPaisaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimarActionPerformed
        Thread h1 = new Thread(this);
        h1.start();
        AlgoritmoSolucion al = new AlgoritmoSolucion(7);
        al.resolverVector();
    }//GEN-LAST:event_btnAnimarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Algoritmo del barquero, algoritmo aplicado a 7 animales.");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enemigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enemigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enemigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enemigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enemigos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBote;
    private javax.swing.JLabel lblCol;
    private javax.swing.JLabel lblHalcon;
    private javax.swing.JLabel lblLechuga;
    private javax.swing.JLabel lblMantis;
    private javax.swing.JLabel lblPaisaje;
    private javax.swing.JLabel lblRaton;
    private javax.swing.JLabel lblSaltamontes;
    private javax.swing.JLabel lblSerpiente;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        
        for(int i = 0; i<5; i++){
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Enemigos.class.getName()).log(Level.SEVERE, null, ex);
            }
            switch (i){
                case 0:
                     lblMantis.setLocation(370, 290);
                     lblSerpiente.setLocation(440, 290);
                     lblSaltamontes.setLocation(500,290 );
                     break;
                case 1:
                     lblLechuga.setLocation(400, 290);
                     lblRaton.setLocation(470, 290);
                     lblCol.setLocation(540, 290);
                     break;
                case 2:
                    lblMantis.setLocation(220, 270);
                    lblSerpiente.setLocation(120, 270);
                    lblSaltamontes.setLocation(240,290 );
                    break;
                case 3:
                    lblHalcon.setLocation(570, 290);
                    break;
                case 4:
                    lblMantis.setLocation(370, 290);
                    lblSerpiente.setLocation(440, 290);
                    lblSaltamontes.setLocation(500,290 );
                    break;
            }
 
        }
        
    }
    
}
